import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const CONTENT_WIDTH = SCREEN_WIDTH * 0.9;
const DELETE_WIDTH = 80;

export const lightStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  contentContainer: {
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    paddingTop: 80,
    backgroundColor: '#FFFFFF',
    width: '100%',
  },
  headerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#000000',
    fontFamily: 'Futura',
    marginLeft: 16,
    left: 55,
    top: -4,
  },
  textInput: {
    height: 200,
    width: CONTENT_WIDTH,
    borderColor: '#000000',
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    marginBottom: 16,
    textAlignVertical: 'top',
    marginTop: 10,
    color: '#000000',
    backgroundColor: '#FFFFFF',
  },
  timeSettings: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    width: CONTENT_WIDTH,
  },
  label: {
    fontSize: 16,
    marginRight: 8,
    color: '#000000',
  },
  timeInput: {
    borderColor: '#000000',
    borderWidth: 1,
    borderRadius: 4,
    padding: 4,
    width: 50,
    fontSize: 16,
    textAlign: 'center',
    color: '#000000',
    backgroundColor: '#FFFFFF',
  },
  saveButton: {
    backgroundColor: '#F0F0F0',
    borderColor: '#000000',
    borderWidth: 2,
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginBottom: 20,
    width: CONTENT_WIDTH,
  },
  saveButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
  },
  savedSpeechesHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    width: CONTENT_WIDTH,
    color: '#000000',
  },
  savedSpeechItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F0F0',
    borderColor: '#000000',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    width: CONTENT_WIDTH,
  },
  savedSpeechNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 10,
    color: '#000000',
  },
  savedSpeechText: {
    flex: 1,
    fontSize: 16,
    color: '#000000',
  },
  noSpeechesText: {
    fontSize: 16,
    fontStyle: 'italic',
    textAlign: 'center',
    width: CONTENT_WIDTH,
    color: '#000000',
  },
  deleteButton: {
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    width: DELETE_WIDTH,
    height: 50,
    borderRadius: 8,
    borderColor: '#000000',
    borderWidth: 1,
  },
});